version: '3.1'
services:

  odoo:
    image: odoopbx/odoo:${ODOO_VERSION:-15.0}
    build:
      context: ../../addons
      args:
        ODOO_VERSION: ${ODOO_VERSION:-15.0}

  pbx:
    image: odoopbx/pbx:latest
    build:
      dockerfile: ./docker/Dockerfile
      context: ../
