version: '3.1'
services:

  odoo:
    image: odoopbx/odoo:${ODOO_VERSION:-14}
    build:
      context: ../../addons
      args:
        ODOO_VERSION: ${ODOO_VERSION:-14}

  agent:
    image: odoopbx/agent:1.0
    build:
      dockerfile: ./docker/agent/Dockerfile
      context: ../

  asterisk:
    image: odoopbx/asterisk:16.8-cert12
    build:
      dockerfile: ./docker/asterisk/Dockerfile
      context: ..
