version: '3.1'
services:

  odoo:
    image: odoopbx/odoo:${ODOO_VERSION:-14}
    build:
      dockerfile: ./odoo/Dockerfile
      context: ./
      args:
        ODOO_VERSION: ${ODOO_VERSION:-14}
  
  agent:
    image: odoopbx/agent:${AGENT_VERSION:-latest}
    build:
      dockerfile: ./docker/agent/Dockerfile
      context: ../

  asterisk:
    image: odoopbx/asterisk:16.8-cert12
    build:
      dockerfile: ./docker/asterisk/Dockerfile
      context: ..
