version: '3.1'
services:

  db:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata

  odoo:
    depends_on:
      - db
    image: odoopbx/odoo:${ODOO_VERSION:-15.0}
    command: odoo -d ${ODOO_DB:-odoopbx_15}
    environment:
    - HOST=db
    - USER=odoo
    - PASSWORD=odoo
    - DATABASE=${ODOO_DB:-odoopbx_15}
    - ODOO_VERSION
    volumes:
      - odoo_data:/var/lib/odoo
    ports:
      - 0.0.0.0:8072:8072

  agent:
    image: odoopbx/pbx
    ipc: host
    # Required to manage host's ipsets (if reactor is enabled).
    privileged: true
    volumes:
      - ./salt.conf:/etc/supervisor/conf.d/salt.conf
      - asterisk_spool:/var/spool/asterisk
      - asterisk_etc:/etc/asterisk
      - asterisk_run:/var/run/asterisk
    ports:
      - 0.0.0.0:30000:30000
    environment:
      - ODOO_DB


  asterisk:
    image: odoopbx/pbx
    privileged: true
    volumes:
      - ./asterisk.conf:/etc/supervisor/conf.d/asterisk.conf
      - asterisk_spool:/var/spool/asterisk
      - asterisk_etc:/etc/asterisk
      - asterisk_run:/var/run/asterisk
    ports:
      - 0.0.0.0:65060:65060/udp
      - 0.0.0.0:10100-10200:10100-10200/udp
      - 0.0.0.0:8089:8089

  freepbx:
    # https://hub.docker.com/r/tiredofit/freepbx. See also:
    # https://github.com/tiredofit/docker-freepbx/blob/15/examples/docker-compose.yml
    image: tiredofit/freepbx
    cap_add:
      - NET_ADMIN
    privileged: True
    volumes:
      - freepbx_data:/data
      - freepbx_db:/var/lib/mysql
    environment:
      - DB_EMBEDDED=TRUE


volumes:
  odoo_data:
  db_data:
  asterisk_etc:
  asterisk_run:
  asterisk_spool:
  freepbx_db:
  freepbx_data:
