version: '3.1'
services:

  db:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata

  odoo:
    depends_on:
      - db
    image: odoopbx/odoo:${ODOO_VERSION:-14}
    command: odoo -d ${ODOO_DB:-odoopbx_14}
    environment:
    - HOST=db
    - USER=odoo
    - PASSWORD=odoo
    - DATABASE=${ODOO_DB:-odoopbx_14}
    volumes:
      - odoo_data:/var/lib/odoo

  agent:
    image: odoopbx/agent:1.0
    ipc: host
    # Required to manage host's ipsets (if reactor is enabled).
    privileged: true
    volumes:
      - asterisk_spool:/var/spool/asterisk
      - asterisk_etc:/etc/asterisk
    environment:
      - ODOO_DB=${ODOO_DB:-odoopbx_14}

  asterisk:
    image: odoopbx/asterisk:16.8-cert12
    privileged: true
    volumes:
      - asterisk_spool:/var/spool/asterisk
      - asterisk_etc:/etc/asterisk

  freepbx:
    # https://hub.docker.com/r/tiredofit/freepbx. See also:
    # https://github.com/tiredofit/docker-freepbx/blob/15/examples/docker-compose.yml
    image: tiredofit/freepbx
    cap_add:
      - NET_ADMIN
    privileged: True
    volumes:
      - freepbx_data:/data
      - freepbx_db:/var/lib/mysql
    environment:
      - DB_EMBEDDED=TRUE


volumes:
  odoo_data:
  db_data:
  asterisk_etc:
  asterisk_spool:
  freepbx_db:
  freepbx_data:
