name: CI
on:
  push:
    branches:
      - master

jobs:
  Build-Odoo:
    runs-on: ubuntu-20.04
    steps:
      - run: x=y echo $x
      - run: echo $x
      - run: echo "${{ github.repositoryUrl }}"
      - run: echo "${{ github.event_name }} event in ${{ github.repository }} ${{ github.ref }}"
      - run: echo "${{ secrets.DOCKERHUB_USERNAME }} asdf ${{ secrets.t1env.DOCKERHUB_USERNAME }}"
      - name: Docker Hub Login
        uses: docker/login-action@v1
        with:
          username: litnialex
          password: be83d663-0434-43af-950d-f3cc0c5be92f
      - name: Build Odoo
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.repositoryUrl }}:docker
          file: odoo/Dockerfile
          push: true
          tags: litnialex/odoo:latest
